version: '3.8'

services:
  api-test:
    build:
      context: ./api-service
      dockerfile: Dockerfile.test
    container_name: ml-sales-api-test
    volumes:
      - ./api-service/htmlcov:/app/htmlcov
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=test
    networks:
      - test-network

networks:
  test-network:
    driver: bridge

