# Development overrides
# This file is automatically merged with docker-compose.yml in development

version: '3.8'

services:
  api:
    # Enable hot reload for development
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      # Mount source code for hot reload
      - ./api-service/app:/app/app
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG

