version: '3.8'

services:
  api:
    build:
      context: ./api-service
      dockerfile: Dockerfile
    container_name: ml-sales-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
    volumes:
      - ./api-service/models:/app/models:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ml-sales-network

networks:
  ml-sales-network:
    driver: bridge

