version: '3.8'

services:
  api:
    build:
      context: ./api-service
      dockerfile: Dockerfile
    container_name: ml-sales-api
    ports:
      - "8000:8000"
    volumes:
      # Hot reload in development
      - ./api-service/app:/app/app:ro
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ml-network
    restart: unless-stopped

networks:
  ml-network:
    driver: bridge
