[tool.black]
line-length = 88
target-version = ['py313']
include = '\.pyi?$'
extend-exclude = '''
/(
  | venv
  | __pycache__
  | .pytest_cache
  | htmlcov
  | models
)/
'''

[tool.isort]
profile = "black"
line_length = 88
skip_gitignore = true

